# Generated by Django 3.2.4 on 2021-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
