# Generated by Django 3.2.4 on 2021-09-08 09:37

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import foxstraat.core.accounts.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('object_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_fake_profile', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_blogger', models.BooleanField(default=False)),
                ('gelt', models.IntegerField(default=0)),
                ('num_posts', models.PositiveIntegerField(default=0)),
                ('username', foxstraat.core.accounts.models.LowercaseCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='accounts/profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=3000, null=True)),
                ('subscribers', models.PositiveBigIntegerField(default=1)),
                ('upvotes', models.PositiveBigIntegerField(default=0)),
                ('instagram', models.CharField(blank=True, max_length=60, null=True)),
                ('vsco', models.CharField(blank=True, max_length=60, null=True)),
                ('twitter', models.CharField(blank=True, max_length=60, null=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('default_styles', models.TextField(default='\n<style>\n    /* \n    You can edit other HTML Tags\' styles.\n    This Google font is a part of our branding. \n    YOU ARE NOT ALLOWED TO CHANGE THIS FONT */\n    @import url("https://fonts.googleapis.com/css2?family=Lobster&display=swap");\n    /* Fonts used in this page. You can change these. */\n    @import url(\'https://use.fontawesome.com/releases/v5.0.7/css/all.css\');\n\n    /* Branding styles begin */\n    .logo {\n        font-size: 2em !important;\n        color: #212121;\n        padding: 10px 16px;\n        text-decoration: none;\n        float: left;\n        font-family: "Lobster", cursive;\n    }\n    /* Branding styles end */\n\n    .container {\n        margin: 7rem 7rem;\n    }\n\n    /* Navbar styles */\n    .navbar {\n        overflow: hidden;\n        background-color: #fff;\n        box-shadow: 0 3px 5px 0 rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.08);\n        position: fixed;\n        top: 0;\n        left: 0;\n        width: 100%;\n    }\n\n    .nav-links {\n        float: left;\n        font-weight: 600;\n        font-family: Arial, Helvetica, sans-serif;\n        margin-top: 10px;\n        display: block;\n        color: #212121;\n        font-size: 1em;\n      \ttext-transform: capitalize;\n        text-align: center;\n        text-decoration: none;\n        padding: 14px 16px;\n    }\n\n    .nav-links:hover {\n        background: transparent;\n    }\n    /* Navbar styles end */\n\n    .section-heading {\n        font-family: Arial, Helvetica, sans-serif;\n        color: #212121;\n    }\n\n    /* User basic info styles */\n    .user-details-basic-container {\n        margin-top: 1rem;\n        width: 100%;\n    }\n\n    .profile-image-container {\n        margin-right: 3rem;\n        margin-top: 1rem;\n    }\n\n    .profile-picture {\n        object-fit: cover;\n        width: 240px;\n        height: 240px;\n    }\n\n    .username-container {\n        margin-top: 5px;\n    }\n\n    .username {\n        margin-bottom: 0;\n        font-family: Arial, Helvetica, sans-serif;\n        font-size: 1.8em;\n        font-weight: 600 !important;\n    }\n\n    .user-stat-container {\n        margin-top: 5px;\n    }\n\n    .stat {\n        float: left;\n        display: block;\n        font-size: 0.9em;\n        font-family: Arial, Helvetica, sans-serif;\n        color: rgb(155, 155, 155);\n        font-weight: 700;\n        margin-right: 1em !important;\n    }\n    /* user basic info styles end */\n\n    /* user advanced info styles start */\n    .user-details-advanced-container {\n        width: 100%;\n    }\n\n    .social-links-container {\n        margin-top: 5px;\n    }\n\n    .social-link {\n        text-decoration: none;\n        color: rgb(118, 118, 134);\n        font-weight: 600;\n        font-size: 1.2em;\n        margin-right: 15px;\n    }\n\n    .bio-container {\n        margin-top: 2rem;\n    }\n\n    .bio {\n        font-family: Arial, Helvetica, sans-serif;\n        color: #333333;\n        font-weight: 500;\n        white-space: pre-wrap;\n    }\n    /* user advanced info styles end */\n\n    /* Post image styles */\n    .post-image {\n        width: 260px;\n        height: 260px;\n        margin-bottom: 1.5rem;\n        object-fit: cover;\n    }\n    /* post image styles end */\n</style>\n        ')),
                ('custom_styles', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('datetime_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
