# Generated by Django 3.2.4 on 2021-09-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gelt',
            field=models.IntegerField(default=500),
        ),
    ]
