# Generated by Django 3.2.4 on 2021-09-15 09:52

from django.db import migrations
import foxstraat.core.accounts.models
import foxstraat.core.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=foxstraat.core.accounts.models.LowercaseCharField(error_messages={'unique': 'This email address already has an account associated with it'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=300, unique=True, validators=[foxstraat.core.accounts.validators.UnicodeEmailValidator()], verbose_name='email address'),
        ),
    ]
