# Generated by Django 3.2.4 on 2021-09-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gelt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_artist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blogger',
        ),
    ]
