# Generated by Django 3.2.4 on 2021-09-14 13:12

import django.contrib.auth.validators
from django.db import migrations, models
import foxstraat.core.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=foxstraat.core.accounts.models.LowercaseCharField(error_messages={'unique': 'This email address already has an account associated with it'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=300, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
