# Generated by Django 3.2.4 on 2021-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultWebsites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, max_length=20000, null=True)),
                ('domain', models.CharField(blank=True, max_length=200000, null=True)),
                ('path', models.CharField(blank=True, max_length=20000, null=True)),
                ('subdomain', models.CharField(blank=True, max_length=20000, null=True)),
                ('host', models.CharField(blank=True, max_length=20000, null=True)),
                ('tld', models.CharField(blank=True, max_length=20000, null=True)),
                ('parent_domain', models.CharField(blank=True, max_length=20000, null=True)),
            ],
        ),
    ]
