# Generated by Django 3.2.4 on 2021-09-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ref',
        ),
    ]
