# Generated by Django 3.2.4 on 2021-09-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adultwebsites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdultWebsites',
            new_name='ForbiddenWebsites',
        ),
    ]
