# Generated by Django 3.2.4 on 2021-09-08 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=280)),
                ('screenshot_1', imagekit.models.fields.ProcessedImageField(upload_to='marketplace/templates/')),
                ('screenshot_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='marketplace/templates/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('template', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
