# Generated by Django 3.2.4 on 2021-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField(max_length=140)),
                ('is_default', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField(max_length=140)),
                ('is_default', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
