# Generated by Django 3.2.4 on 2021-09-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAnnouncement',
        ),
    ]
